executorImage: argoproj/argoexec:v2.2.0
artifactRepository:
  s3:
    bucket: mlpipeline
    keyPrefix: artifacts
    endpoint: minio:9000
    insecure: true
    accessKeySecret:
      name: mlpipeline-minio-artifact
      key: accesskey
    secretKeySecret:
      name: mlpipeline-minio-artifact
      key: secretkey
