dist: xenial
language: python
python: 3.7
sudo: required
env:
  global:
    - BUILD=true
    - CI=true
    - CHARM_BUILD_DIR=/tmp/charm-builds
  matrix:
    - JUJU_CHANNEL=stable
    - JUJU_CHANNEL=edge
install:
  - sudo systemctl stop docker.service
  - sudo apt purge libyaml-dev
  - sudo apt install libffi6 libffi-dev
  - sudo snap install charm --classic
  - sudo snap install juju --classic --channel $JUJU_CHANNEL
  - sudo snap install juju-wait --classic
  - sudo snap install juju-helpers --classic --edge
  - sudo snap alias juju-helpers.juju-bundle juju-bundle
  - sudo snap install microk8s --classic
  - sudo microk8s.status --wait-ready --timeout 60
  - pip install pytest pyyaml requests sh cffi black==19.3b0
script:
  - git config --global --unset protocol.version 2
  # Run regular deploy script
  - ./scripts/deploy-microk8s.sh

  # Make Ambassador available and run tests
  - microk8s.kubectl port-forward svc/ambassador -n kubeflow 8081:80 &
  - pytest
  - black . --check
after_failure:
  - microk8s.kubectl get pods --all-namespaces
  - juju status --format yaml
