options:
  port:
    type: int
    default: 8085
    description: HTTP port
  username:
    type: string
    default: 'admin'
    description: HTTP Basic Auth username
  password:
    type: string
    default: ''
    description: HTTP Basic Auth password
