kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: k8s-ebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
