options:
  bucket:
    type: string
    default: mlpipeline
    description: S3 bucket name
  key-prefix:
    type: string
    default: artifacts
    description: S3 key prefix
  repo-access-key:
    type: string
    default: minio
    description: Artifact repository access key
  repo-secret-key:
    type: string
    default: minio123
    description: Artifact repository secret key
  executor:
    type: string
    default: kubelet
    description: |
      Runtime executor for workflow containers. One of `docker` or `kubelet`.
      If your cluster is using containerd, this must be set to `kubelet`.
  kubelet-insecure:
    type: boolean
    default: true
    description: |
      If true, Argo will skip checking kubelet's TLS certificate. Has no effect
      with other executors.
