options:
  bucket:
    type: string
    default: mlpipeline
    description: S3 bucket name
  key-prefix:
    type: string
    default: artifacts
    description: S3 key prefix
  repo-access-key:
    type: string
    default: minio
    description: Artifact repository access key
  repo-secret-key:
    type: string
    default: minio123
    description: Artifact repository secret key
  executor:
    type: string
    default: pns
    description: |
      Runtime executor for workflow containers. Cannot be `docker` on containerd,
      for a full list of executors, see https://github.com/argoproj/argo/tree/master/workflow/executor
  kubelet-insecure:
    type: boolean
    default: false
    description: |
      If true, Argo will skip checking kubelet's TLS certificate. Has no effect
      with other executors.
