options:
  root-password:
    description: |
      Password to use for the database root user. If not specified,
      one will be generated automatically.
    type: string
    default: ''
  database:
    type: string
    default: defaultdb
    description: The database to create
  port:
    type: int
    default: 3306
    description: The port to listen to
