name: delete-aws-volumes.yaml
on:
  push:
    branches:
      - main

jobs:
  delete-volumes:
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v2
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUNDLE_KUBEFLOW_EKS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUNDLE_KUBEFLOW_EKS_AWS_SECRET_ACCESS_KEY
            }}
        name: Configure AWS Credentials
        run: 'aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID

          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

          aws configure set default.region eu-central-1

          '
      - id: measurement-3
        name: Record Measurement After Configure AWS Credentials
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Configure AWS Credentials
          task: get-measurement
      - name: Install requirements
        run: 'python -m pip install --upgrade pip

          pip install boto3

          pip install tenacity

          '
      - id: measurement-5
        name: Record Measurement After Install requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install requirements
          task: get-measurement
      - name: Run delete volumes script
        run: python scripts/delete_volumes.py ${{ inputs.region }}
      - id: measurement-7
        name: Record Measurement After Run delete volumes script
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run delete volumes script
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
