name: Publish
on:
  push:
    branches:
      - master
      - main
      - track/**
  pull_request:
    branches:
      - master
      - main
      - track/**

jobs:
  publish-bundle:
    name: Publish bundle-kubeflow
    runs-on: ubuntu-latest
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    steps:
      #FIXME: this will only publish the kubeflow bundle, no edge/lite
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo snap install charmcraft --classic --channel=latest/edge
      - name: Pack and publish bundle
        run: |
          set -ex
          charmcraft pack --destructive-mode
          charmcraft upload ./*.zip
          export REVISION=$(charmcraft revisions kubeflow 2>&1 | awk 'NR==2 {print $1}')
          charmcraft release kubeflow --revision $REVISION --channel=latest/edge



