name: release-bundle-to-charmhub.yaml
on:
  push:
    branches:
      - main

jobs:
  get-releases-affected:
    name: Get releases affected
    outputs:
      releases_affected: ${{ steps.get-releases-affected.outputs.releases_affected_json
        }}
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed-files
        name: Get files changed
        uses: tj-actions/changed-files@v37
      - id: get-releases-affected
        name: Get releases affected
        run: python scripts/get_releases_affected.py ${{ steps.changed-files.outputs.all_changed_files
          }}
      - id: measurement-4
        name: Record Measurement After Get releases affected
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get releases affected
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  run-tests-and-publish-bundle-for-releases-affected:
    name: Run bundle tests and publish to Charmhub
    needs:
      - get-releases-affected
    secrets: inherit
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        release: ${{ fromJson(needs.get-releases-affected.outputs.releases_affected)
          }}
    uses: ./.github/workflows/run-tests-and-publish-bundle.yaml
    with:
      release: ${{ matrix.release }}
