name: run-tests-and-publish-bundle.yaml
on:
  push:
    branches:
      - main

jobs:
  get-release-inputs:
    name: Get required inputs
    outputs:
      bundle_path: ${{ steps.bundle-path.outputs.bundle_path }}
      bundle_test_path: ${{ steps.bundle-test-path.outputs.bundle_test_path }}
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
      - id: bundle-path
        name: Get bundle path for ${{ inputs.release }}
        run: python scripts/get_bundle_path.py ${{ inputs.release }}
      - id: measurement-3
        name: Record Measurement After Get bundle path for ${{ inputs.release }}
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get bundle path for ${{ inputs.release }}
          task: get-measurement
      - id: bundle-test-path
        name: Get bundle test path for ${{ inputs.release }}
        run: python scripts/get_bundle_test_path.py ${{ inputs.release }}
      - id: measurement-5
        name: Record Measurement After Get bundle test path for ${{ inputs.release
          }}
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get bundle test path for ${{ inputs.release }}
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  publish-bundle-for-releases-affected:
    name: Publish bundle
    needs:
      - get-release-inputs
    runs-on: ubuntu-22.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v3
      - name: Publish bundle release ${{ inputs.release }}
        uses: canonical/charming-actions/upload-bundle@2.6.3
        with:
          bundle-path: ${{ needs.get-release-inputs.outputs.bundle_path }}
          channel: ${{ inputs.release }}
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
