name: scan-images.yaml

on:
  push:
    branches:
      - main

jobs:
  scan-images:
    strategy:
      fail-fast: false
      matrix:
        bundle-path:
          - 1.8/stable/kubeflow
          - 1.9/stable
          - latest/edge
    uses: ./.github/workflows/get-images-and-scan.yaml
    with:
      bundle-directory: ${{ matrix.bundle-path }}

  measure-energy:
    needs: scan-images
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption-scan-images
          path: total_energy_consumption.json